### ISSUE TITLE
can not run "MicroRTSGridModeVecEnv(...)"

### ISSUE THREAD

**Issue by ZJJ2017** [vwxyzjn/gym-microrts#12]
When I run "hello_world.py", the error messages are as follow:
    from rts.units import UnitTypeTable
    ImportError: cannot import name 'UnitTypeTable' from 'rts.units' (unknown location)

**Comment by vwxyzjn** [comment]
You need to recursively clone the project 

git clone --recursive https://github.com/vwxyzjn/gym-microrts.git

Check out developer guide here: https://github.com/vwxyzjn/gym-microrts#developer-guide

**Comment by ZJJ2017** [comment]
I have recursively cloned the project and followed the developer guide to build the microrts.
But the question emerged when I run it on Win10.

**Comment by vwxyzjn** [comment]
Can you try the pypi installation: pip install gym_microrts —upgrade

I had recently tested the pypi installation at least that worked on win 10

Sincerely,
Costa
________________________________

**Comment by ZJJ2017** [comment]
The way of pypi installation worked on win10. 
The above-mentioned question appeared,  when I followed the developer guide.
Can you tell me how to solve the problem?

**Comment by vwxyzjn** [comment]
Did you build the microrts? So it is


pip install gym_microrts --upgrade


Sincerely,
Costa
________________________________

**Comment by vwxyzjn** [comment]
It is

cd gym_microrts/microrts && bash build.sh && cd ..&& cd ..
python hello_world.py



Sincerely,
Costa
________________________________

**Comment by ZJJ2017** [comment]
I have used the following commands to build the microrts.
cd gym_microrts/microrts && bash build.sh && cd ..&& cd ..

But when I run hello_world.py, the problem appeared.

**Comment by ZJJ2017** [comment]
I have used the following commands to build the microrts.
cd gym_microrts/microrts && bash build.sh && cd ..&& cd ..

But when I run hello_world.py, the problem appeared.

**Comment by vwxyzjn** [comment]
Could you check if an microrts.jar has been created? If so could you check if it has the correct classes built in? What’s your jdk version

Sincerely,
Costa
________________________________

**Comment by ZJJ2017** [comment]
microrts.jar has been created.
My jdk version is 15.01

**Comment by vwxyzjn** [comment]
Could you check the content of the `microrts.jar` file? Mine looks like 

![image](https://user-images.githubusercontent.com/5555347/125475715-1895d9a3-0233-4265-8154-401e2d6325ff.png)

**Comment by ZJJ2017** [comment]
![image](https://user-images.githubusercontent.com/31504672/125476947-7df59b9e-5c00-41a8-90d0-737a3b1e59b7.png)

**Comment by vwxyzjn** [comment]
Ah so something went wrong there. You don't have the ai folder in there. I just pushed my latest changes. Could you pull recursively and rebuild microrts?

**Comment by vwxyzjn** [comment]
I apologize for the inconvenience. For future, I will start doing PRs to not break master.

**Comment by ZJJ2017** [comment]
I have pulled recursively and rebuilt microrts just now, but the same problem still appeared.

![image](https://user-images.githubusercontent.com/31504672/125484522-9c51c0f3-7378-4935-810b-4b7b4422bcf6.png)

![image](https://user-images.githubusercontent.com/31504672/125484591-ad3a9000-2b57-45f4-9761-2a8b3359b539.png)

**Comment by vwxyzjn** [comment]
Try `cd gym_microrts/microrts && bash build.sh > build.log && cd ..&& cd ..
python hello_world.py`, and check the `build.log` to see if there is any error over there, maybe. Also are you using the bash to run the script above in windows?

**Comment by ZJJ2017** [comment]
There is not  a file named 'build.log'.
When I was building microrts, there is no any error messages.

**Comment by ZJJ2017** [comment]
I think that there may be some errors in the following command.
javac -d "./build" -cp "./lib/*" -sourcepath "./src"  $(find ./src/* | grep .java)

**Comment by balloch** [comment]
I am also facing this problem. Is there a tagged earlier version pre-breaking change that
 we can work in ?

**Comment by vwxyzjn** [comment]
Hey is this on windows?

**Comment by vwxyzjn** [comment]
If you are on windows, you could try building microrts using bash instead of Powershell

**Comment by vwxyzjn** [comment]
Also you could run the one with pebuild jars by doing

pip install gym_microrts —upgrade

**Comment by balloch** [comment]
I'm on Linux not windows, and the pip install method is what I tried to use

**Comment by vwxyzjn** [comment]
@balloch oh wow that is very unexpected. When you installed through pip, have you tried to run the hello world code in a directory that is not in this repo?

**Comment by vwxyzjn** [comment]
https://asciinema.org/a/GpgHDe0ysLR1eNVpJrDHCFyJd 

Here you go. At least pip installation should work.

**Comment by balloch** [comment]
Yes the hello world is what is causing the error for me

**Comment by vwxyzjn** [comment]
If you checkout the video recording at https://asciinema.org/a/GpgHDe0ysLR1eNVpJrDHCFyJd, it shows that you can install via pip and then it runs the hello_world.py without problems.

**Comment by vwxyzjn** [comment]
These are the commands that are associated with the video recording  at https://asciinema.org/a/GpgHDe0ysLR1eNVpJrDHCFyJd

```bash
asciinema rec
docker run -it ubuntu bash 

# wait until the docker bash appears then do commands below
apt-get update && apt-get -y install python3 python3-pip xvfb default-jdk curl
pip install gym_microrts==0.4.2
curl -OL https://raw.githubusercontent.com/vwxyzjn/gym-microrts/4a8098811fc871a456041b3357f284359c466572/hello_world.py
python3 hello_world.py
```

**Comment by balloch** [comment]
Thanks, I'll check it out, try specifying the version to pip and see if it
helps

**Comment by balloch** [comment]
What version of Ubuntu is in the video (or if not Ubuntu which kernel?)

**Comment by vwxyzjn** [comment]
I think by default it's using `20.04(latest)`

**Comment by vwxyzjn** [comment]
Closing this but feel free to reopen
